const PVP_QUESTIONS = [
  { prompt: '¿Cómo se dice "perro" en inglés?', options: ['Dog', 'Cat', 'Bird', 'Fish'], correct: 'Dog' },
  { prompt: '¿Cuál es la traducción de "agua"?', options: ['Fire', 'Water', 'Air', 'Earth'], correct: 'Water' },
  { prompt: '¿Cómo se dice "libro" en inglés?', options: ['Book', 'Table', 'Chair', 'Door'], correct: 'Book' },
  { prompt: '¿Qué significa "friend"?', options: ['Enemigo', 'Amigo', 'Familia', 'Extraño'], correct: 'Amigo' },
  { prompt: '¿Cómo se dice "escuela" en inglés?', options: ['Hospital', 'School', 'Church', 'Market'], correct: 'School' },
  { prompt: '¿Cuál es la traducción de "rojo"?', options: ['Blue', 'Green', 'Red', 'Yellow'], correct: 'Red' },
  { prompt: '¿Cómo se dice "comer" en inglés?', options: ['Drink', 'Sleep', 'Eat', 'Run'], correct: 'Eat' },
  { prompt: '¿Qué significa "big"?', options: ['Pequeño', 'Grande', 'Mediano', 'Largo'], correct: 'Grande' },
  { prompt: '¿Cómo se dice "madre" en inglés?', options: ['Father', 'Sister', 'Mother', 'Brother'], correct: 'Mother' },
  { prompt: '¿Cuál es la traducción de "tiempo"?', options: ['Space', 'Time', 'Place', 'World'], correct: 'Time' },
  { prompt: '¿Cómo se dice "trabajo" en inglés?', options: ['Job', 'Home', 'Game', 'Party'], correct: 'Job' },
  { prompt: '¿Qué significa "fast"?', options: ['Lento', 'Rápido', 'Fuerte', 'Suave'], correct: 'Rápido' },
  { prompt: '¿Cómo se dice "ciudad" en inglés?', options: ['Town', 'City', 'Village', 'Country'], correct: 'City' },
  { prompt: '¿Cuál es la traducción de "mano"?', options: ['Foot', 'Head', 'Hand', 'Arm'], correct: 'Hand' },
  { prompt: '¿Cómo se dice "feliz" en inglés?', options: ['Sad', 'Angry', 'Happy', 'Tired'], correct: 'Happy' },
  { prompt: 'Completa: "She ___ English every day"', options: ['study', 'studies', 'studying', 'studys'], correct: 'studies' },
  { prompt: 'Completa: "I ___ to the gym on Mondays"', options: ['go', 'goes', 'going', 'gos'], correct: 'go' },
  { prompt: 'Completa: "They ___ coffee in the morning"', options: ['drinks', 'drink', 'drinking', 'drinked'], correct: 'drink' },
  { prompt: 'Completa: "He ___ television at night"', options: ['watch', 'watches', 'watching', 'watchs'], correct: 'watches' },
  { prompt: 'Completa: "We ___ from Mexico"', options: ['come', 'comes', 'coming', 'comed'], correct: 'come' },
  { prompt: 'Completa: "The dog ___ loudly"', options: ['bark', 'barks', 'barking', 'barkes'], correct: 'barks' },
  { prompt: 'Completa: "My sister ___ a doctor"', options: ['is', 'are', 'am', 'be'], correct: 'is' },
  { prompt: 'Completa: "You ___ very kind"', options: ['is', 'are', 'am', 'be'], correct: 'are' },
  { prompt: 'Completa: "It ___ raining outside"', options: ['is', 'are', 'am', 'be'], correct: 'is' },
  { prompt: 'Completa: "I ___ not like spicy food"', options: ['do', 'does', 'am', 'is'], correct: 'do' },
  { prompt: '¿Cuál es el pasado de "run"?', options: ['runned', 'ran', 'runed', 'running'], correct: 'ran' },
  { prompt: '¿Cuál es el pasado de "see"?', options: ['seed', 'saw', 'seen', 'seeing'], correct: 'saw' },
  { prompt: '¿Cuál es el pasado de "take"?', options: ['taked', 'tooked', 'took', 'taken'], correct: 'took' },
  { prompt: '¿Cuál es el pasado de "make"?', options: ['maked', 'made', 'maken', 'making'], correct: 'made' },
  { prompt: '¿Cuál es el pasado de "come"?', options: ['comed', 'came', 'coming', 'comen'], correct: 'came' },
  { prompt: '¿Cuál es el pasado de "give"?', options: ['gived', 'gave', 'given', 'giving'], correct: 'gave' },
  { prompt: '¿Cuál es el pasado de "speak"?', options: ['speaked', 'spoke', 'spoken', 'speaking'], correct: 'spoke' },
  { prompt: '¿Cuál es el pasado de "begin"?', options: ['beginned', 'began', 'begun', 'beginning'], correct: 'began' },
  { prompt: '¿Cuál es el pasado de "drink"?', options: ['drinked', 'drank', 'drunk', 'drinking'], correct: 'drank' },
  { prompt: '¿Cuál es el pasado de "fly"?', options: ['flyed', 'flew', 'flown', 'flying'], correct: 'flew' },
  { prompt: '¿Qué palabra en inglés significa "dónde"?', options: ['When', 'Where', 'Why', 'What'], correct: 'Where' },
  { prompt: '¿Qué palabra en inglés significa "cuándo"?', options: ['Where', 'When', 'Why', 'How'], correct: 'When' },
  { prompt: '¿Qué palabra en inglés significa "por qué"?', options: ['What', 'When', 'Why', 'Who'], correct: 'Why' },
  { prompt: '¿Qué palabra en inglés significa "cómo"?', options: ['How', 'What', 'When', 'Where'], correct: 'How' },
  { prompt: '¿Qué palabra en inglés significa "cuánto"?', options: ['How many', 'How old', 'How long', 'How far'], correct: 'How many' },
  { prompt: '¿Qué palabra en inglés significa "cuál"?', options: ['Which', 'Where', 'When', 'Why'], correct: 'Which' },
  { prompt: '¿Qué palabra en inglés significa "de quién"?', options: ['Who', 'Whose', 'Which', 'Whom'], correct: 'Whose' },
  { prompt: '¿Cuál es el opuesto de "tall"?', options: ['Short', 'Long', 'Wide', 'Thin'], correct: 'Short' },
  { prompt: '¿Cuál es el opuesto de "fast"?', options: ['Quick', 'Slow', 'Late', 'Early'], correct: 'Slow' },
  { prompt: '¿Cuál es el opuesto de "happy"?', options: ['Excited', 'Sad', 'Angry', 'Scared'], correct: 'Sad' },
  { prompt: '¿Cuál es el opuesto de "young"?', options: ['New', 'Old', 'Big', 'Small'], correct: 'Old' },
  { prompt: '¿Cuál es el opuesto de "open"?', options: ['Close', 'Shut', 'Locked', 'Hidden'], correct: 'Shut' },
  { prompt: '¿Cuál es el opuesto de "rich"?', options: ['Wealthy', 'Poor', 'Cheap', 'Expensive'], correct: 'Poor' },
  { prompt: '¿Cuál es el opuesto de "light"?', options: ['Bright', 'Dark', 'Heavy', 'Soft'], correct: 'Dark' },
  { prompt: '¿Cuál es el opuesto de "clean"?', options: ['Neat', 'Dirty', 'Wet', 'Dry'], correct: 'Dirty' },
  { prompt: '¿Cuál es el opuesto de "easy"?', options: ['Simple', 'Hard', 'Light', 'Soft'], correct: 'Hard' },
  { prompt: '¿Cuál es el opuesto de "full"?', options: ['Complete', 'Empty', 'Heavy', 'Light'], correct: 'Empty' },
  { prompt: 'Completa: "The book is ___ the table"', options: ['in', 'on', 'at', 'by'], correct: 'on' },
  { prompt: 'Completa: "I live ___ Madrid"', options: ['in', 'on', 'at', 'by'], correct: 'in' },
  { prompt: 'Completa: "The cat is ___ the box"', options: ['in', 'on', 'at', 'by'], correct: 'in' },
  { prompt: 'Completa: "We go to school ___ bus"', options: ['in', 'on', 'by', 'at'], correct: 'by' },
  { prompt: 'Completa: "He is standing ___ the door"', options: ['in', 'at', 'on', 'by'], correct: 'at' },
  { prompt: 'Completa: "The picture is ___ the wall"', options: ['in', 'on', 'at', 'by'], correct: 'on' },
  { prompt: 'Completa: "I was born ___ January"', options: ['in', 'on', 'at', 'by'], correct: 'in' },
  { prompt: 'Completa: "___ apple a day keeps the doctor away"', options: ['A', 'An', 'The', 'No article'], correct: 'An' },
  { prompt: 'Completa: "She is ___ honest woman"', options: ['A', 'An', 'The', 'No article'], correct: 'An' },
  { prompt: 'Completa: "I saw ___ elephant at the zoo"', options: ['A', 'An', 'The', 'No article'], correct: 'An' },
  { prompt: 'Completa: "He plays ___ guitar very well"', options: ['A', 'An', 'The', 'No article'], correct: 'The' },
  { prompt: 'Completa: "___ sun rises in the east"', options: ['A', 'An', 'The', 'No article'], correct: 'The' },
  { prompt: '¿Qué significa "dangerous"?', options: ['Seguro', 'Peligroso', 'Difícil', 'Fácil'], correct: 'Peligroso' },
  { prompt: '¿Cómo se dice "inteligente" en inglés?', options: ['Intelligent', 'Important', 'Interesting', 'Incredible'], correct: 'Intelligent' },
  { prompt: '¿Qué significa "expensive"?', options: ['Barato', 'Caro', 'Nuevo', 'Viejo'], correct: 'Caro' },
  { prompt: '¿Cómo se dice "cansado" en inglés?', options: ['Tired', 'Bored', 'Worried', 'Excited'], correct: 'Tired' },
  { prompt: '¿Qué significa "hungry"?', options: ['Sediento', 'Hambriento', 'Cansado', 'Enojado'], correct: 'Hambriento' },
  { prompt: '¿Cuál es el pronombre objeto de "he"?', options: ['Him', 'Her', 'His', 'He'], correct: 'Him' },
  { prompt: '¿Cuál es el pronombre posesivo de "they"?', options: ['Their', 'There', 'They', 'Them'], correct: 'Their' },
  { prompt: 'Completa: "This is ___ book, not yours"', options: ['my', 'me', 'I', 'mine'], correct: 'my' },
  { prompt: 'Completa: "She loves ___ children very much"', options: ['her', 'she', 'hers', 'she\'s'], correct: 'her' },
  { prompt: '¿Cuál es el pronombre objeto de "we"?', options: ['Us', 'Our', 'We', 'Ours'], correct: 'Us' },
  { prompt: '¿Qué significa "How are you?"', options: ['¿Cómo te llamas?', '¿Cómo estás?', '¿Cuántos años tienes?', '¿Dónde vives?'], correct: '¿Cómo estás?' },
  { prompt: '¿Cómo se dice "por favor" en inglés?', options: ['Thank you', 'Please', 'Sorry', 'Excuse me'], correct: 'Please' },
  { prompt: '¿Qué significa "good morning"?', options: ['Buenas noches', 'Buenas tardes', 'Buenos días', 'Buen viaje'], correct: 'Buenos días' },
  { prompt: '¿Qué significa "see you later"?', options: ['Hasta nunca', 'Hasta pronto', 'Hasta luego', 'Buenas noches'], correct: 'Hasta luego' },
  { prompt: '¿Cómo se dice "árbol" en inglés?', options: ['Tree', 'Flower', 'Grass', 'Leaf'], correct: 'Tree' },
  { prompt: '¿Qué significa "kitchen"?', options: ['Dormitorio', 'Cocina', 'Baño', 'Sala'], correct: 'Cocina' },
  { prompt: '¿Cómo se dice "mariposa" en inglés?', options: ['Bee', 'Butterfly', 'Spider', 'Ant'], correct: 'Butterfly' },
  { prompt: '¿Qué significa "shoe"?', options: ['Camisa', 'Zapato', 'Pantalón', 'Sombrero'], correct: 'Zapato' },
  { prompt: '¿Cómo se dice "llave" en inglés?', options: ['Key', 'Lock', 'Door', 'Window'], correct: 'Key' },
  { prompt: '¿Qué significa "beach"?', options: ['Montaña', 'Playa', 'Río', 'Lago'], correct: 'Playa' },
  { prompt: '¿Cómo se dice "estrella" en inglés?', options: ['Moon', 'Sun', 'Star', 'Sky'], correct: 'Star' },
  { prompt: '¿Qué significa "garden"?', options: ['Jardín', 'Casa', 'Calle', 'Parque'], correct: 'Jardín' },
  { prompt: '¿Cómo se dice "nariz" en inglés?', options: ['Mouth', 'Nose', 'Ear', 'Eye'], correct: 'Nose' },
  { prompt: '¿Qué significa "weekend"?', options: ['Semana', 'Fin de semana', 'Día festivo', 'Vacaciones'], correct: 'Fin de semana' },
  { prompt: '¿Cómo se dice "cien" en inglés?', options: ['One hundred', 'One thousand', 'Ten', 'One million'], correct: 'One hundred' },
  { prompt: '¿Qué significa "fifteen"?', options: ['Cincuenta', 'Quince', 'Cinco', 'Quinto'], correct: 'Quince' },
  { prompt: '¿Cómo se dice "miércoles" en inglés?', options: ['Monday', 'Wednesday', 'Friday', 'Tuesday'], correct: 'Wednesday' },
  { prompt: '¿Qué significa "February"?', options: ['Enero', 'Febrero', 'Marzo', 'Abril'], correct: 'Febrero' },
  { prompt: '¿Cuál es el comparativo de "bad"?', options: ['badder', 'worse', 'more bad', 'worst'], correct: 'worse' },
  { prompt: '¿Cuál es el superlativo de "far"?', options: ['farthest', 'more far', 'farest', 'most far'], correct: 'farthest' },
  { prompt: '¿Cuál es el comparativo de "comfortable"?', options: ['comfortabler', 'more comfortable', 'most comfortable', 'comfortablest'], correct: 'more comfortable' },
  { prompt: '¿Cuál es el superlativo de "intelligent"?', options: ['intelligentest', 'most intelligent', 'more intelligent', 'intelligentmost'], correct: 'most intelligent' },
  { prompt: 'Completa: "This test is ___ than the last one"', options: ['difficulter', 'more difficult', 'most difficult', 'difficultest'], correct: 'more difficult' },
  { prompt: 'Completa: "She is the ___ student in the class"', options: ['better', 'goodest', 'best', 'more good'], correct: 'best' },
  { prompt: 'Completa: "My car is ___ expensive than yours"', options: ['most', 'more', 'much', 'less'], correct: 'less' },
  { prompt: 'Completa: "He runs ___ than his brother"', options: ['fastest', 'more fast', 'faster', 'more faster'], correct: 'faster' },
  { prompt: 'Completa: "I ___ studying when you called"', options: ['was', 'were', 'am', 'been'], correct: 'was' },
  { prompt: 'Completa: "They ___ been waiting for an hour"', options: ['has', 'have', 'had', 'having'], correct: 'have' },
  { prompt: 'Completa: "She ___ living in Paris since 2020"', options: ['has been', 'have been', 'had been', 'is been'], correct: 'has been' },
  { prompt: 'Completa: "We ___ already eaten when he arrived"', options: ['has', 'have', 'had', 'having'], correct: 'had' },
  { prompt: 'Completa: "By next year, I ___ graduated"', options: ['will have', 'will be', 'will', 'would have'], correct: 'will have' },
  { prompt: 'Completa: "He ___ working here for ten years"', options: ['has been', 'have been', 'had been', 'is being'], correct: 'has been' },
  { prompt: 'Completa: "While I was cooking, she ___ the table"', options: ['sets', 'set', 'was setting', 'is setting'], correct: 'was setting' },
  { prompt: 'Completa: "They ___ never been to Japan"', options: ['has', 'have', 'had', 'are'], correct: 'have' },
  { prompt: 'Completa: "I ___ my homework before I went out"', options: ['finish', 'finished', 'had finished', 'have finished'], correct: 'had finished' },
  { prompt: 'Completa: "She ___ English since she was five"', options: ['learns', 'learned', 'has been learning', 'is learning'], correct: 'has been learning' },
  { prompt: 'Completa: "If it rains, I ___ stay home"', options: ['will', 'would', 'should', 'could'], correct: 'will' },
  { prompt: 'Completa: "If she studied more, she ___ pass"', options: ['will', 'would', 'can', 'shall'], correct: 'would' },
  { prompt: 'Completa: "If I had known, I ___ have helped you"', options: ['will', 'would', 'should', 'could'], correct: 'would' },
  { prompt: 'Completa: "If he ___ harder, he would have succeeded"', options: ['tried', 'had tried', 'tries', 'trying'], correct: 'had tried' },
  { prompt: 'Completa: "If you heat water, it ___"', options: ['boils', 'boiled', 'would boil', 'will boil'], correct: 'boils' },
  { prompt: 'Completa: "If I were you, I ___ accept the offer"', options: ['will', 'would', 'shall', 'can'], correct: 'would' },
  { prompt: 'Completa: "If she calls, tell her I ___ back later"', options: ['call', 'called', 'will call', 'would call'], correct: 'will call' },
  { prompt: 'Completa: "She is interested ___ learning French"', options: ['on', 'in', 'at', 'for'], correct: 'in' },
  { prompt: 'Completa: "He depends ___ his parents"', options: ['of', 'on', 'in', 'for'], correct: 'on' },
  { prompt: 'Completa: "She complained ___ the noise"', options: ['about', 'for', 'of', 'on'], correct: 'about' },
  { prompt: 'Completa: "He succeeded ___ passing the exam"', options: ['on', 'at', 'in', 'for'], correct: 'in' },
  { prompt: 'Completa: "They agreed ___ the plan"', options: ['with', 'on', 'about', 'for'], correct: 'on' },
  { prompt: 'Completa: "She reminded me ___ the appointment"', options: ['about', 'of', 'for', 'on'], correct: 'of' },
  { prompt: '¿Qué significa "however"?', options: ['Por lo tanto', 'Sin embargo', 'Además', 'Porque'], correct: 'Sin embargo' },
  { prompt: '¿Qué significa "therefore"?', options: ['Por lo tanto', 'Sin embargo', 'Además', 'Aunque'], correct: 'Por lo tanto' },
  { prompt: '¿Qué significa "furthermore"?', options: ['Además', 'Sin embargo', 'Por lo tanto', 'En cambio'], correct: 'Además' },
  { prompt: '¿Qué significa "nevertheless"?', options: ['Nunca', 'No obstante', 'Siempre', 'Además'], correct: 'No obstante' },
  { prompt: '¿Qué significa "otherwise"?', options: ['De otra manera', 'Por lo tanto', 'Además', 'Siempre'], correct: 'De otra manera' },
  { prompt: '¿Qué significa "provided that"?', options: ['Proporcionado', 'Siempre que / Con tal de que', 'Prohibido', 'Provisto'], correct: 'Siempre que / Con tal de que' },
  { prompt: '¿Qué significa "besides"?', options: ['Además', 'Excepto', 'Sin embargo', 'Porque'], correct: 'Además' },
  { prompt: '¿Qué significa "instead"?', options: ['En su lugar', 'Además', 'Por lo tanto', 'Siempre'], correct: 'En su lugar' },
  { prompt: '¿Qué significa "give up"?', options: ['Dar', 'Rendirse', 'Levantarse', 'Crecer'], correct: 'Rendirse' },
  { prompt: '¿Qué significa "look after"?', options: ['Buscar', 'Cuidar', 'Mirar', 'Esperar'], correct: 'Cuidar' },
  { prompt: '¿Qué significa "turn on"?', options: ['Apagar', 'Encender', 'Girar', 'Subir'], correct: 'Encender' },
  { prompt: '¿Qué significa "take off"?', options: ['Ponerse', 'Quitarse', 'Llevar', 'Tomar'], correct: 'Quitarse' },
  { prompt: '¿Qué significa "look forward to"?', options: ['Mirar adelante', 'Esperar con ansias', 'Dar la vuelta', 'Buscar'], correct: 'Esperar con ansias' },
  { prompt: '¿Qué significa "put off"?', options: ['Poner', 'Posponer', 'Quitarse', 'Apagar'], correct: 'Posponer' },
  { prompt: '¿Qué significa "bring up"?', options: ['Traer arriba', 'Mencionar / Criar', 'Llevar', 'Quitar'], correct: 'Mencionar / Criar' },
  { prompt: '¿Qué significa "carry out"?', options: ['Llevar fuera', 'Realizar / Llevar a cabo', 'Cargar', 'Continuar'], correct: 'Realizar / Llevar a cabo' },
  { prompt: '¿Qué significa "figure out"?', options: ['Cifrar', 'Entender / Resolver', 'Imaginar', 'Calcular'], correct: 'Entender / Resolver' },
  { prompt: '¿Qué significa "run out of"?', options: ['Correr fuera', 'Quedarse sin', 'Escapar', 'Agotar energía'], correct: 'Quedarse sin' },
  { prompt: '¿Qué significa "hardly"?', options: ['Duramente', 'Apenas', 'Fuertemente', 'Fácilmente'], correct: 'Apenas' },
  { prompt: '¿Qué significa "nowadays"?', options: ['Ahora mismo', 'Hoy en día', 'De vez en cuando', 'Nunca'], correct: 'Hoy en día' },
  { prompt: '¿Qué significa "somehow"?', options: ['Alguien', 'De alguna manera', 'Algo', 'A veces'], correct: 'De alguna manera' },
  { prompt: '¿Qué significa "seldom"?', options: ['Siempre', 'Rara vez', 'A menudo', 'Nunca'], correct: 'Rara vez' },
  { prompt: '¿Qué significa "quite"?', options: ['Tranquilo', 'Bastante', 'Silencioso', 'Nada'], correct: 'Bastante' },
  { prompt: '¿Qué significa "increasingly"?', options: ['Crecientemente', 'Rápidamente', 'Lentamente', 'Seguramente'], correct: 'Crecientemente' },
  { prompt: '¿Cuál es el plural de "mouse"?', options: ['mouses', 'mice', 'mices', 'meese'], correct: 'mice' },
  { prompt: '¿Cuál es el plural de "tooth"?', options: ['tooths', 'teeth', 'teeths', 'toothes'], correct: 'teeth' },
  { prompt: '¿Cuál es el plural de "foot"?', options: ['foots', 'feet', 'feets', 'footes'], correct: 'feet' },
  { prompt: '¿Cuál es el plural de "person"?', options: ['persons', 'people', 'peoples', 'persones'], correct: 'people' },
  { prompt: '¿Cuál es el plural de "ox"?', options: ['oxes', 'oxen', 'oxens', 'oxies'], correct: 'oxen' },
  { prompt: '¿Cuál es el plural de "sheep"?', options: ['sheeps', 'sheep', 'sheepes', 'sheepies'], correct: 'sheep' },
  { prompt: '¿Cuál es el plural de "fish"?', options: ['fishes', 'fish', 'fishs', 'fishes'], correct: 'fish' },
  { prompt: '¿Cuál es el plural de "goose"?', options: ['gooses', 'geese', 'geeses', 'goosies'], correct: 'geese' },
  { prompt: '¿Cuál es el plural de "man"?', options: ['mans', 'men', 'mens', 'mannies'], correct: 'men' },
  { prompt: '¿Cuál es el plural de "woman"?', options: ['womans', 'women', 'womens', 'womans'], correct: 'women' },
  { prompt: '¿Qué significa "achieve"?', options: ['Fallar', 'Lograr', 'Perder', 'Olvidar'], correct: 'Lograr' },
  { prompt: '¿Cómo se dice "desarrollo" en inglés?', options: ['Development', 'Departure', 'Decision', 'Delivery'], correct: 'Development' },
  { prompt: '¿Qué significa "aware"?', options: ['Asustado', 'Consciente', 'Cansado', 'Aburrido'], correct: 'Consciente' },
  { prompt: '¿Cómo se dice "ventaja" en inglés?', options: ['Adventure', 'Advantage', 'Advice', 'Advance'], correct: 'Advantage' },
  { prompt: '¿Qué significa "decision"?', options: ['Decisión', 'Discusión', 'Descripción', 'Dirección'], correct: 'Decisión' },
  { prompt: '¿Cómo se dice "conocimiento" en inglés?', options: ['Knowledge', 'Knee', 'Knock', 'Knife'], correct: 'Knowledge' },
  { prompt: '¿Qué significa "environment"?', options: ['Entorno / Medio ambiente', 'Entretenimiento', 'Energía', 'Empresa'], correct: 'Entorno / Medio ambiente' },
  { prompt: '¿Cómo se dice "comportamiento" en inglés?', options: ['Behavior', 'Belief', 'Benefit', 'Beginning'], correct: 'Behavior' },
  { prompt: '¿Qué significa "research"?', options: ['Búsqueda', 'Investigación', 'Reserva', 'Recurso'], correct: 'Investigación' },
  { prompt: '¿Cómo se dice "oportunidad" en inglés?', options: ['Opportunity', 'Operation', 'Option', 'Opinion'], correct: 'Opportunity' },
  { prompt: 'Completa: "The woman ___ called you is my aunt"', options: ['who', 'which', 'whom', 'whose'], correct: 'who' },
  { prompt: 'Completa: "The book ___ I read was fascinating"', options: ['who', 'which', 'whom', 'whose'], correct: 'which' },
  { prompt: 'Completa: "The girl ___ bag was stolen is crying"', options: ['who', 'which', 'whose', 'whom'], correct: 'whose' },
  { prompt: 'Completa: "To ___ did you give the letter?"', options: ['who', 'which', 'whom', 'whose'], correct: 'whom' },
  { prompt: 'Completa: "___ of you wants to come?"', options: ['Who', 'Which', 'Whom', 'Whose'], correct: 'Which' },
  { prompt: 'Completa: "I did it ___"', options: ['myself', 'himself', 'herself', 'themselves'], correct: 'myself' },
  { prompt: 'Completa: "She enjoys ___ novels"', options: ['read', 'reading', 'to read', 'reads'], correct: 'reading' },
  { prompt: 'Completa: "He decided ___ abroad"', options: ['study', 'studying', 'to study', 'studied'], correct: 'to study' },
  { prompt: 'Completa: "I want ___ the truth"', options: ['know', 'knowing', 'to know', 'knew'], correct: 'to know' },
  { prompt: 'Completa: "They suggested ___ early"', options: ['leave', 'leaving', 'to leave', 'left'], correct: 'leaving' },
  { prompt: 'Completa: "She made him ___ the room"', options: ['clean', 'cleaning', 'to clean', 'cleaned'], correct: 'clean' },
  { prompt: 'Completa: "He is used to ___ up early"', options: ['get', 'getting', 'to get', 'got'], correct: 'getting' },
  { prompt: 'Completa: "She used to ___ in London"', options: ['live', 'living', 'to live', 'lived'], correct: 'live' },
  { prompt: '¿Qué significa "stubborn"?', options: ['Amable', 'Terco', 'Tímido', 'Generoso'], correct: 'Terco' },
  { prompt: '¿Qué significa "reliable"?', options: ['Religioso', 'Confiable', 'Relajado', 'Relacionado'], correct: 'Confiable' },
  { prompt: '¿Qué significa "wealthy"?', options: ['Saludable', 'Adinerado', 'Sabio', 'Cálido'], correct: 'Adinerado' },
  { prompt: '¿Qué significa "genuine"?', options: ['Genérico', 'Auténtico', 'Gentil', 'Grande'], correct: 'Auténtico' },
  { prompt: '¿Qué significa "bitter"?', options: ['Mejor', 'Amargo', 'Brillante', 'Blando'], correct: 'Amargo' },
  { prompt: '¿Qué significa "shallow"?', options: ['Oscuro', 'Sombrío', 'Superficial', 'Profundo'], correct: 'Superficial' },
  { prompt: '¿Qué significa "to beat around the bush"?', options: ['Golpear el arbusto', 'Irse por las ramas', 'Correr rápido', 'Perder el tiempo'], correct: 'Irse por las ramas' },
  { prompt: '¿Qué significa "to break the ice"?', options: ['Romper el hielo literalmente', 'Romper el silencio incómodo', 'Hacer frío', 'Congelarse'], correct: 'Romper el silencio incómodo' },
  { prompt: '¿Qué significa "a piece of cake"?', options: ['Un trozo de pastel', 'Muy fácil', 'Muy difícil', 'Un regalo'], correct: 'Muy fácil' },
  { prompt: '¿Qué significa "to let the cat out of the bag"?', options: ['Dejar salir al gato', 'Revelar un secreto', 'Perder algo', 'Asustarse'], correct: 'Revelar un secreto' },
  { prompt: '¿Qué significa "once in a blue moon"?', options: ['Cada luna azul', 'Muy raramente', 'Una vez al mes', 'Siempre'], correct: 'Muy raramente' },
  { prompt: '¿Qué significa "to hit the nail on the head"?', options: ['Golpear el clavo', 'Dar en el clavo / Acertar', 'Cometer un error', 'Construir algo'], correct: 'Dar en el clavo / Acertar' },
  { prompt: '¿Qué significa "the last straw"?', options: ['La última paja', 'La gota que colmó el vaso', 'El último intento', 'La última oportunidad'], correct: 'La gota que colmó el vaso' },
  { prompt: '¿Qué significa "to burn the midnight oil"?', options: ['Quemar aceite', 'Estudiar/trabajar hasta tarde', 'Cocinar de noche', 'Gastar dinero'], correct: 'Estudiar/trabajar hasta tarde' },
  { prompt: '¿Qué significa "to spill the beans"?', options: ['Derramar frijoles', 'Revelar un secreto', 'Cocinar', 'Hacer un desastre'], correct: 'Revelar un secreto' },
  { prompt: '¿Qué significa "to be on cloud nine"?', options: ['Estar en una nube', 'Estar extremadamente feliz', 'Estar confundido', 'Estar enfermo'], correct: 'Estar extremadamente feliz' },
  { prompt: '¿Qué significa "to bite the bullet"?', options: ['Morder la bala', 'Enfrentar algo difícil con valentía', 'Disparar', 'Esconderse'], correct: 'Enfrentar algo difícil con valentía' },
  { prompt: '¿Qué significa "under the weather"?', options: ['Bajo el clima', 'Enfermo / Indispuesto', 'Al aire libre', 'Con mal tiempo'], correct: 'Enfermo / Indispuesto' },
  { prompt: '¿Qué significa "to cut corners"?', options: ['Cortar esquinas', 'Hacer algo de forma rápida y mal', 'Cortar papel', 'Dar la vuelta'], correct: 'Hacer algo de forma rápida y mal' },
  { prompt: '¿Qué significa "to be on the fence"?', options: ['Estar en la cerca', 'Estar indeciso', 'Estar seguro', 'Estar enojado'], correct: 'Estar indeciso' },
  { prompt: '¿Qué significa "to come across"?', options: ['Cruzar', 'Encontrarse con algo/alguien', 'Venir a través', 'Acercarse'], correct: 'Encontrarse con algo/alguien' },
  { prompt: '¿Qué significa "to get away with"?', options: ['Escapar con', 'Salir impune de algo', 'Llevarse algo', 'Acercarse'], correct: 'Salir impune de algo' },
  { prompt: '¿Qué significa "to look into"?', options: ['Mirar dentro', 'Investigar', 'Buscar adentro', 'Enfocar'], correct: 'Investigar' },
  { prompt: '¿Qué significa "to put up with"?', options: ['Poner arriba', 'Tolerar / Soportar', 'Construir', 'Levantar'], correct: 'Tolerar / Soportar' },
  { prompt: '¿Qué significa "to turn out"?', options: ['Apagar', 'Resultar / Salir', 'Girar', 'Devolver'], correct: 'Resultar / Salir' },
  { prompt: '¿Qué significa "to bring about"?', options: ['Traer', 'Causar / Provocar', 'Llevar', 'Recordar'], correct: 'Causar / Provocar' },
  { prompt: '¿Qué significa "to lay off"?', options: ['Acostar', 'Despedir trabajadores', 'Dejar de hacer', 'Poner encima'], correct: 'Despedir trabajadores' },
  { prompt: '¿Qué significa "to stand for"?', options: ['Pararse para', 'Representar / Significar', 'Soportar de pie', 'Esperar'], correct: 'Representar / Significar' },
  { prompt: '¿Qué significa "to weed out"?', options: ['Cultivar', 'Eliminar / Descartar', 'Plantar', 'Arrancar maleza literal'], correct: 'Eliminar / Descartar' },
  { prompt: '¿Qué significa "to boil down to"?', options: ['Hervir', 'Reducirse a / Resumirse en', 'Bajar', 'Cocinar'], correct: 'Reducirse a / Resumirse en' },
  { prompt: 'Completa: "Had I known, I ___ have acted differently"', options: ['will', 'would', 'should', 'could'], correct: 'would' },
  { prompt: 'Completa: "I wish I ___ harder when I was young"', options: ['study', 'studied', 'had studied', 'would study'], correct: 'had studied' },
  { prompt: 'Completa: "If only she ___ the truth"', options: ['knows', 'knew', 'known', 'knowing'], correct: 'knew' },
  { prompt: 'Completa: "Suppose he ___ late, what would happen?"', options: ['arrives', 'arrived', 'arriving', 'arrive'], correct: 'arrived' },
  { prompt: 'Completa: "But for your help, I ___ have failed"', options: ['will', 'would', 'shall', 'can'], correct: 'would' },
  { prompt: 'Completa: "She suggested that he ___ a doctor"', options: ['sees', 'see', 'saw', 'seen'], correct: 'see' },
  { prompt: 'Completa: "I insist that she ___ on time"', options: ['is', 'be', 'was', 'were'], correct: 'be' },
  { prompt: 'Completa: "Were she here, she ___ agree"', options: ['will', 'would', 'shall', 'can'], correct: 'would' },
  { prompt: '¿Qué significa "ubiquitous"?', options: ['Único', 'Ubicuo / Presente en todas partes', 'Desconocido', 'Raro'], correct: 'Ubicuo / Presente en todas partes' },
  { prompt: '¿Qué significa "pragmatic"?', options: ['Idealista', 'Pragmático / Práctico', 'Pesimista', 'Optimista'], correct: 'Pragmático / Práctico' },
  { prompt: '¿Qué significa "resilient"?', options: ['Resistente / Capaz de recuperarse', 'Rígido', 'Relajado', 'Resignado'], correct: 'Resistente / Capaz de recuperarse' },
  { prompt: '¿Qué significa "ambiguous"?', options: ['Ambicioso', 'Ambiguo / Con varios significados', 'Amable', 'Amplio'], correct: 'Ambiguo / Con varios significados' },
  { prompt: '¿Qué significa "inevitable"?', options: ['Increíble', 'Inevitable / Imposible de evitar', 'Invisible', 'Innovador'], correct: 'Inevitable / Imposible de evitar' },
  { prompt: '¿Qué significa "meticulous"?', options: ['Métrico', 'Meticuloso / Detallista', 'Mínimo', 'Militar'], correct: 'Meticuloso / Detallista' },
  { prompt: '¿Qué significa "profound"?', options: ['Profesional', 'Profundo', 'Promedio', 'Propio'], correct: 'Profundo' },
  { prompt: '¿Qué significa "perpetual"?', options: ['Perfecto', 'Perpetuo / Continuo', 'Perezoso', 'Peligroso'], correct: 'Perpetuo / Continuo' },
  { prompt: '¿Qué significa "eloquent"?', options: ['Eléctrico', 'Elocuente / Persuasivo al hablar', 'Elegante', 'Eliminado'], correct: 'Elocuente / Persuasivo al hablar' },
  { prompt: '¿Qué significa "lucrative"?', options: ['Lúcido', 'Lucrativo / Rentable', 'Luminoso', 'Lógico'], correct: 'Lucrativo / Rentable' },
  { prompt: '¿Qué significa "detrimental"?', options: ['Determinante', 'Perjudicial', 'Detallado', 'Determinado'], correct: 'Perjudicial' },
  { prompt: '¿Qué significa "unprecedented"?', options: ['Impredecible', 'Sin precedentes', 'Inútil', 'Invisible'], correct: 'Sin precedentes' },
  { prompt: '¿Qué significa "scrutinize"?', options: ['Escribir', 'Examinar detenidamente', 'Esconder', 'Saltar'], correct: 'Examinar detenidamente' },
  { prompt: '¿Qué significa "mitigate"?', options: ['Crear', 'Mitigar / Suavizar', 'Destruir', 'Ignorar'], correct: 'Mitigar / Suavizar' },
  { prompt: '¿Qué significa "exacerbate"?', options: ['Exagerar', 'Empeorar / Exacerbar', 'Excelente', 'Excluir'], correct: 'Empeorar / Exacerbar' },
  { prompt: '¿Qué significa "notwithstanding"?', options: ['No obstante', 'No congelado', 'No obstante / A pesar de', 'Nunca'], correct: 'No obstante / A pesar de' },
  { prompt: '¿Qué significa "hence"?', options: ['De aquí', 'Por lo tanto / De aquí que', 'Hasta', 'Hace'], correct: 'Por lo tanto / De aquí que' },
  { prompt: '¿Qué significa "whereby"?', options: ['Donde sea', 'Mediante el cual', 'Cuándo', 'Por qué'], correct: 'Mediante el cual' },
  { prompt: '¿Qué significa "thereby"?', options: ['Allí', 'Con ello / De ese modo', 'Por lo tanto', 'Después'], correct: 'Con ello / De ese modo' },
  { prompt: '¿Qué significa "albeit"?', options: ['Todo', 'Aunque / A pesar de que', 'Además', 'Después'], correct: 'Aunque / A pesar de que' },
  { prompt: '¿Qué significa "inasmuch as"?', options: ['En cuanto a', 'En la medida en que', 'Además de', 'A pesar de'], correct: 'En la medida en que' },
  { prompt: '¿Qué significa "insofar as"?', options: ['Tan lejos como', 'En la medida en que', 'Lejos de', 'Cerca de'], correct: 'En la medida en que' },
  { prompt: '¿Qué significa "ergo"?', options: ['Error', 'Por lo tanto', 'Energía', 'Nunca'], correct: 'Por lo tanto' },
  { prompt: 'Completa: "Not only ___ she intelligent, but also kind"', options: ['is', 'does', 'was', 'did'], correct: 'is' },
  { prompt: 'Completa: "Rarely ___ I seen such beauty"', options: ['have', 'has', 'had', 'do'], correct: 'have' },
  { prompt: 'Completa: "Seldom ___ he complain about anything"', options: ['do', 'does', 'did', 'has'], correct: 'does' },
  { prompt: 'Completa: "No sooner had I arrived ___ it started to rain"', options: ['that', 'when', 'than', 'then'], correct: 'than' },
  { prompt: 'Completa: "Hardly ___ she entered when the phone rang"', options: ['has', 'had', 'did', 'was'], correct: 'had' },
  { prompt: 'Completa: "Only then ___ I understand the truth"', options: ['do', 'did', 'does', 'was'], correct: 'did' },
  { prompt: '¿Cuál es el participio pasado de "swim"?', options: ['swimmed', 'swam', 'swum', 'swimming'], correct: 'swum' },
  { prompt: '¿Cuál es el participio pasado de "lie" (echarse)?', options: ['lied', 'lay', 'lain', 'lying'], correct: 'lain' },
  { prompt: '¿Cuál es el participio pasado de "shrink"?', options: ['shrinked', 'shrunk', 'shrank', 'shrinking'], correct: 'shrunk' },
  { prompt: '¿Cuál es el participio pasado de "stink"?', options: ['stinked', 'stank', 'stunk', 'stinking'], correct: 'stunk' },
  { prompt: '¿Cuál es el participio pasado de "tear"?', options: ['teared', 'tore', 'torn', 'tearing'], correct: 'torn' },
  { prompt: '¿Cuál es el participio pasado de "weave"?', options: ['weaved', 'wove', 'woven', 'weaving'], correct: 'woven' },
  { prompt: '¿Cuál es el participio pasado de "slay"?', options: ['slayed', 'slew', 'slain', 'slaying'], correct: 'slain' },
  { prompt: '¿Cuál es el participio pasado de "strew"?', options: ['strewed', 'strew', 'strewn', 'strewing'], correct: 'strewn' },
  { prompt: 'Completa: "___ of the students passed the exam"', options: ['Every', 'Each', 'All', 'Both'], correct: 'All' },
  { prompt: 'Completa: "She has ___ time nor patience for this"', options: ['neither', 'either', 'both', 'none'], correct: 'neither' },
  { prompt: 'Completa: "I have two pens. ___ is blue and ___ is red"', options: ['One / the other', 'One / another', 'Some / other', 'Each / every'], correct: 'One / the other' },
  { prompt: 'Completa: "___ the candidates were qualified"', options: ['Both of', 'Both', 'Every', 'Each'], correct: 'Both of' },
  { prompt: 'Completa: "There is ___ hope left"', options: ['little', 'a little', 'few', 'a few'], correct: 'little' },
  { prompt: 'Completa: "___ people attended the event"', options: ['Few', 'Little', 'Much', 'Less'], correct: 'Few' },
  { prompt: '¿Qué significa "to take something for granted"?', options: ['Agradecer algo', 'Dar algo por sentado', 'Tomar algo prestado', 'Rechazar algo'], correct: 'Dar algo por sentado' },
  { prompt: '¿Qué significa "to make ends meet"?', options: ['Hacer amigos', 'Llegar a fin de mes', 'Terminar algo', 'Comenzar algo'], correct: 'Llegar a fin de mes' },
  { prompt: '¿Qué significa "to keep a low profile"?', options: ['Ser famoso', 'Mantener un perfil bajo', 'Ser alto', 'Hablar fuerte'], correct: 'Mantener un perfil bajo' },
  { prompt: '¿Qué significa "by and large"?', options: ['Grande y pequeño', 'En general', 'Poco a poco', 'De vez en cuando'], correct: 'En general' },
  { prompt: '¿Qué significa "to be in two minds"?', options: ['Tener dos mentes', 'Estar indeciso', 'Ser inteligente', 'Estar loco'], correct: 'Estar indeciso' },
  { prompt: '¿Qué significa "to go the extra mile"?', options: ['Caminar más', 'Esfuerzarse más de lo esperado', 'Viajar lejos', 'Correr una milla'], correct: 'Esfuerzarse más de lo esperado' },
  { prompt: '¿Qué significa "to draw the line"?', options: ['Dibujar una línea', 'Poner un límite', 'Cancelar algo', 'Empezar algo'], correct: 'Poner un límite' },
  { prompt: '¿Qué significa "to be on the same page"?', options: ['Leer lo mismo', 'Estar de acuerdo', 'Estar en la misma hoja', 'Escribir igual'], correct: 'Estar de acuerdo' },
  { prompt: 'Completa: "She is incapable ___ lying"', options: ['of', 'for', 'to', 'with'], correct: 'of' },
  { prompt: 'Completa: "He is notorious ___ his temper"', options: ['of', 'for', 'with', 'in'], correct: 'for' },
  { prompt: 'Completa: "They are skeptical ___ the results"', options: ['about', 'for', 'of', 'with'], correct: 'about' },
  { prompt: 'Completa: "The accident resulted ___ three deaths"', options: ['from', 'in', 'of', 'with'], correct: 'in' },
  { prompt: 'Completa: "She attributed her success ___ hard work"', options: ['in', 'to', 'for', 'with'], correct: 'to' },
  { prompt: 'Completa: "He was deprived ___ sleep"', options: ['from', 'of', 'with', 'in'], correct: 'of' },
  { prompt: 'Completa: "They persisted ___ their efforts"', options: ['in', 'on', 'with', 'for'], correct: 'in' },
  { prompt: 'Completa: "She prides herself ___ her cooking"', options: ['in', 'on', 'of', 'for'], correct: 'on' },
  { prompt: '¿Qué significa "ephemeral"?', options: ['Efímero / Pasajero', 'Eterno', 'Eléctrico', 'Elegante'], correct: 'Efímero / Pasajero' },
  { prompt: '¿Qué significa "ostentatious"?', options: ['Ostensivo', 'Ostentoso / Llamativo', 'Oscuro', 'Obvio'], correct: 'Ostentoso / Llamativo' },
  { prompt: '¿Qué significa "gregarious"?', options: ['Grave', 'Gregario / Sociable', 'Greedy', 'Generoso'], correct: 'Gregario / Sociable' },
  { prompt: '¿Qué significa "voracious"?', options: ['Voraz / Insaciable', 'Valiente', 'Variado', 'Vigoroso'], correct: 'Voraz / Insaciable' },
  { prompt: '¿Qué significa "surreptitious"?', options: ['Seguro', 'Subrepticio / Secreto', 'Superior', 'Sorpresa'], correct: 'Subrepticio / Secreto' },
  { prompt: '¿Qué significa "juxtapose"?', options: ['Justificar', 'Yuxtaponer / Colocar lado a lado', 'Jugar', 'Juzgar'], correct: 'Yuxtaponer / Colocar lado a lado' },
  { prompt: '¿Qué significa "capricious"?', options: ['Capaz', 'Caprichoso / Impredecible', 'Cauteloso', 'Caritativo'], correct: 'Caprichoso / Impredecible' },
  { prompt: '¿Qué significa "quintessential"?', options: ['Quintuplicado', 'Quintessential / El ejemplo perfecto', 'Quietud', 'Quimérico'], correct: 'Quintessential / El ejemplo perfecto' },
  { prompt: '¿Qué significa "vicarious"?', options: ['Victorioso', 'Vicario / Experimentado a través de otro', 'Vicioso', 'Visible'], correct: 'Vicario / Experimentado a través de otro' },
  { prompt: '¿Qué significa "conundrum"?', options: ['Conocimiento', 'Acertijo / Problema difícil', 'Conclusión', 'Conversación'], correct: 'Acertijo / Problema difícil' },
  { prompt: '¿Qué significa "to throw in the towel"?', options: ['Tirar la toalla', 'Rendirse', 'Secarse', 'Lavar'], correct: 'Rendirse' },
  { prompt: '¿Qué significa "to be at a crossroads"?', options: ['Estar en una encrucijada / Decisión importante', 'Estar en la calle', 'Estar perdido', 'Estar cruzando'], correct: 'Estar en una encrucijada / Decisión importante' },
  { prompt: '¿Qué significa "to jump the gun"?', options: ['Saltar la pistola', 'Actuar antes de tiempo', 'Disparar', 'Correr rápido'], correct: 'Actuar antes de tiempo' },
  { prompt: '¿Qué significa "to be a dime a dozen"?', options: ['Costar diez centavos', 'Ser muy común / Abundante', 'Ser muy caro', 'Ser doce'], correct: 'Ser muy común / Abundante' },
  { prompt: '¿Qué significa "to call it a day"?', options: ['Llamar al día', 'Terminar por hoy', 'Empezar el día', 'Celebrar'], correct: 'Terminar por hoy' },
  { prompt: '¿Qué significa "to miss the boat"?', options: ['Perder el barco', 'Perder una oportunidad', 'Nadar', 'Navegar'], correct: 'Perder una oportunidad' },
  { prompt: '¿Qué significa "to sit on the fence"?', options: ['Sentarse en la cerca', 'Ser indeciso', 'Descansar', 'Observar'], correct: 'Ser indeciso' },
  { prompt: '¿Qué significa "the ball is in your court"?', options: ['La pelota está en tu cancha', 'Es tu decisión / Te toca a ti', 'Jugar tenis', 'Perder el juego'], correct: 'Es tu decisión / Te toca a ti' },
  { prompt: 'Completa: "So difficult ___ the exam that most students failed"', options: ['was', 'is', 'has been', 'had been'], correct: 'was' },
  { prompt: 'Completa: "Little ___ they know about the danger"', options: ['do', 'did', 'does', 'are'], correct: 'did' },
  { prompt: 'Completa: "Not until he arrived ___ the meeting start"', options: ['does', 'did', 'do', 'was'], correct: 'did' },
  { prompt: 'Completa: "He acts as if he ___ the boss"', options: ['is', 'were', 'was', 'be'], correct: 'were' },
  { prompt: 'Completa: "She speaks as though she ___ everything"', options: ['knows', 'knew', 'known', 'knowing'], correct: 'knew' },
]
